apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: shapeinabox/auth
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.25"
            requests:
              memory: "128Mi"
              cpu: "0.25"
          env:
            - name: MONGO_URI
              value: mongodb://auth-mongo-srv:27017/auth
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth-depl
      protocol: TCP
      port: 3000
      targetPort: 3000
